AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template for Lambda with Playwright.
Resources:
  Playwright:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 30
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Image

      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 ? * MON-FRI *)
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
      DockerTag: v1